-- doing this so verbosely rather than using a loop so that linters more easily pick everything up
return {
    API = require(script:WaitForChild("API")),
    Assembly = require(script:WaitForChild("Assembly")),
    Class = require(script:WaitForChild("Class")),
    ConfigGroup = require(script:WaitForChild("ConfigGroup")),
    Cooldown = require(script:WaitForChild("Cooldown")),
    GUI = require(script:WaitForChild("GUI")),
    Hash = require(script:WaitForChild("Hash")),
    Humanize = require(script:WaitForChild("Humanize")),
    JobId = require(script:WaitForChild("JobId")),
    Maid = require(script:WaitForChild("Maid")),
    Mouse = require(script:WaitForChild("Mouse")),
    Mutex = require(script:WaitForChild("Mutex")),
    Preload = require(script:WaitForChild("Preload")),
    Random = require(script:WaitForChild("Random")),
    ReplicatedValue = require(script:WaitForChild("ReplicatedValue")),
    Time = require(script:WaitForChild("Time")),
    Utils = require(script:WaitForChild("Utils")),
    Vibes = require(script:WaitForChild("Vibes")),
}
